import { Component, OnInit } from '@angular/core';
import { Product } from 'shared/models/product';
import { ProductService } from 'shared/services/product.service';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-product-page',
  templateUrl: './product-page.component.html',
  styleUrls: ['./product-page.component.css']
})
export class ProductPageComponent {

  productId: string;
  product:Product;

  numAvailable:number[];
  quantitySelection: number;
  images = new Array(3).fill(null);


  constructor(private productService: ProductService, private route: ActivatedRoute, private router:Router) { 
      // Subscribe to the route
      route.queryParamMap.subscribe(params => {
        this.productId = params.get('productId');

        window.scroll(0,0);
        
        // Set defaults
        this.quantitySelection = 1;
        this.images.fill(null);

        // Get the product
        productService.get(this.productId).valueChanges().subscribe(
          product=> {
            this.product = product;
            this.numAvailable = Array(this.product.numBuyersRequired-this.product.numBuyers).fill(0).map((x,i)=>i+1);
          
            if(product.images){
              let imageNum = 0;
              for(let img of Object.values(product.images)){
                this.images[imageNum] = img;
                imageNum++;
              }
            }  
          }
        );

      });
    }

    // Takes json object generated by ngForm
    checkout(state){
      this.router.navigate(['/check-out'], 
        { queryParams: 
          { productId: this.productId,
            quantity: state.quantity
          }
      });
    }
}
